"""add column unit_price for order_product_association table

Revision ID: 4069859f8529
Revises: 62aa774beebc
Create Date: 2025-01-24 20:40:56.299695

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4069859f8529"
down_revision: Union[str, None] = "62aa774beebc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "order_product_association",
        sa.Column(
            "unit_price",
            sa.Integer(),
            server_default="0",
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(
        "order_product_association", "unit_price"
    )
    # ### end Alembic commands ###
